
package cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cep", targetNamespace = "http://control/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cep {


    /**
     * 
     * @param cep
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCep", targetNamespace = "http://control/", className = "cliente.ConsultaCep")
    @ResponseWrapper(localName = "consultaCepResponse", targetNamespace = "http://control/", className = "cliente.ConsultaCepResponse")
    @Action(input = "http://control/Cep/consultaCepRequest", output = "http://control/Cep/consultaCepResponse")
    public List<String> consultaCep(
        @WebParam(name = "cep", targetNamespace = "")
        String cep);

}
