
package cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CepService", targetNamespace = "http://control/", wsdlLocation = "http://localhost:10009/cep?wsdl")
public class CepService
    extends Service
{

    private final static URL CEPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CEPSERVICE_EXCEPTION;
    private final static QName CEPSERVICE_QNAME = new QName("http://control/", "CepService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10009/cep?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEPSERVICE_WSDL_LOCATION = url;
        CEPSERVICE_EXCEPTION = e;
    }

    public CepService() {
        super(__getWsdlLocation(), CEPSERVICE_QNAME);
    }

    public CepService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEPSERVICE_QNAME, features);
    }

    public CepService(URL wsdlLocation) {
        super(wsdlLocation, CEPSERVICE_QNAME);
    }

    public CepService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEPSERVICE_QNAME, features);
    }

    public CepService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CepService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cep
     */
    @WebEndpoint(name = "CepPort")
    public Cep getCepPort() {
        return super.getPort(new QName("http://control/", "CepPort"), Cep.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cep
     */
    @WebEndpoint(name = "CepPort")
    public Cep getCepPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://control/", "CepPort"), Cep.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEPSERVICE_EXCEPTION!= null) {
            throw CEPSERVICE_EXCEPTION;
        }
        return CEPSERVICE_WSDL_LOCATION;
    }

}
